### ISSUE TITLE
Version 3.2.2 does not work out of the box with puppet version < 5.0

### ISSUE THREAD

**Issue by sandymcp** [dylanratcliffe/onceover#108]
Running onceover on a Puppet 4.7.0 control-repo gives the environment relative hiera path as
spec/hiera.yaml

Whereby no hiera lookups are working.

IMHO it should be 
hiera.yaml

**Comment by dylanratcliffe** [comment]
@sandymcp Puppet 4.7.0 Supports Hiera 3 & 4, meaning that you can use a hiera v3 file in `spec/hiera.yaml` or a hiera v4 file in `hiera.yaml` (It should just pick it up). It's a bit confusing as 4.7 and other releases were in a kind of limbo where Hiera worked in multiple different ways, plus it all gets changed again in `4.10` when Hiera 5 is released D: If you think there is a bug here please give detail around current and expected behaviour, otherwise I'll close this
