### ISSUE TITLE
Onceover.yaml support for r10k credentials?

### ISSUE THREAD

**Issue by witchbutter** [dylanratcliffe/onceover#166]
I'm having trouble getting onceover to work because I need to add a series of private keys to allow fixtures to be loaded.  Where should private keys be added to prevent r10k from complaining about credentials?

INFO	 -> Updating module /Users/someguy/production/control-repo/.onceover/etc/puppetlabs/code/environments/production/modules/nifty
ERROR	 -> Command exited with non-zero exit code:
Command: git clone --mirror git@bitbucket.org:somecompany/nifty-module.git /Users/someguy/.r10k/git/git@bitbucket.org-somecompany-nifty-module.git
Stderr:
Cloning into bare repository '/Users/someguy/.r10k/git/git@bitbucket.org-somecompany-nifty-module.git'...
git@bitbucket.org: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Exit code: 128

**Comment by dylanratcliffe** [comment]
So r10k should technically work the way it normally does as onceover doesn't really mess with r10k at all. That means that if you create an `r10k.yaml` file at one of [these](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#automatic-configuration) locations, and put [this](https://github.com/puppetlabs/r10k/blob/master/doc/dynamic-environments/configuration.mkd#private_key-1) config in there, it should just work™

**Comment by witchbutter** [comment]
Where r10k.yaml fails, this works:
`ssh-agent $(ssh-add ~/.ssh/private_key); onceover run spec`

**Comment by dylanratcliffe** [comment]
Ah right, it's possible that r10k on the master is using rugged, but when onceover calls it at the command line it's using shellgit which would change the way that this behaves (I think). You may need to try forcing it to use the [rugged provider](https://github.com/puppetlabs/r10k/blob/master/doc/git/providers.mkd) in the `r10k.yaml` file. Which should hopefully give consistent results. Otherwise does the `ssh-agent` workaround solve things?

**Comment by cdenneen** [comment]
Running `onceover show puppetfile` I'm getting 404 for internal modules.
I'm using r10k.yaml in local directory to point to my artifactory instance but output shows it's ignoring this:

```
Error while running: #<Faraday::ResourceNotFound response={:status=>404, :headers=>{"server"=>"nginx", "date"=>"Tue, 09 Oct 2018 20:00:51 GMT", "content-type"=>"application/json", "content-length"=>"36", "connection"=>"close", "etag"=>"\"5bbcc597-24\"", "x-app-server"=>"forgeapi/forgeapi-i-02c9d185ffd47ad6e_forgenext-app09-prod.ops.puppetlabs.net", "x-lb-server"=>"forgenext-lb01-prod.ops.puppetlabs.net", "x-uuid"=>"A5010706:8AB9_0AE0015D:01BB_5BBD08F3_52377AAA:4B2A"}, :body=>"{\n    \"errors\": [\"404 Not found\"]\n}\n"}>
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/response/raise_error.rb:8:in `on_complete'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:9:in `block in call'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:61:in `on_complete'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/response.rb:8:in `call'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/puppet_forge-2.2.9/lib/puppet_forge/middleware/symbolify_json.rb:64:in `call'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:137:in `get'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/puppet_forge-2.2.9/lib/puppet_forge/v3/base.rb:69:in `request'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/puppet_forge-2.2.9/lib/puppet_forge/lazy_accessors.rb:85:in `fetch'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/puppet_forge-2.2.9/lib/puppet_forge/lazy_relations.rb:61:in `block in lazy'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/onceover-3.8.0/lib/onceover/controlrepo.rb:223:in `block (2 levels) in print_puppetfile_table'
/Users/cdenneen/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
```

If I comment out my internal module from my Puppetfile doesn't error, but based on the debug output that's because it's not honoring the r10k.yaml configuration for `forge.baseurl`.

**Comment by dylanratcliffe** [comment]
Hmm. Seems like this is not all falling into place in the way that it should be. Personally for the SSH key issues, I just add them to my ssh-agent and let r10k use shellgit, but that's a bit more of a pain when it comes to build servers, though should be perfectly possible. @witchbutter I would say the workaround for your issue is just to use the ssh-agent for now (i.e. add the keys to your bash profile so you don't have to explicitly load them each time. In the meantime I'm going to create a separate ticket to track the fact that r10k config doesn't seem to be honoured

**Comment by barrymw** [comment]
I'm also faced with the same issue with internally published puppet modules.  The 404 responses for `onceover show puppetfile` is most likely due to the 'noop' implementation done by puppetlabs for the [forge parameter](https://github.com/puppetlabs/r10k/blob/master/doc/puppetfile.mkd#forge).
